### ISSUE TITLE
how to extarct features for Linux profiles

### ISSUE THREAD

**Issue by indtia** [ahlashkari/VolMemLyzer#2]
1. Thanks for preparing this python code for Feature extraction, however i am not able to get the output, my Commands are produced here:
─(inderjeet㉿kali)-[~/volatility3]
└─$ python VolatilityFeatureExtractor.py -o output2.csv  </home/inderjeet/cridex.raw> 
zsh: parse error near `\n'

2. Alos please tell how to use this python code for linux profile, it will be a greta help in my Mtech Reasearch project

**Comment by sharmilaharsha** [comment]
yes same issue here too...
it is not giving any output file in the csv for.

it will be helpful if the authors share this information.

**Comment by ahlashkari** [comment]
Pls, use the V2.0.0.
